# Generated by Django 2.0.2 on 2018-03-12 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attending', models.IntegerField(default=0)),
                ('Total_Time', models.IntegerField(default=0)),
                ('last_checkin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrackName', models.CharField(max_length=500)),
                ('Attendence', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='track.Attendence')),
            ],
        ),
    ]
