# Generated by Django 2.0.2 on 2018-03-13 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrackName', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='track',
            name='TrackName',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='track.Track_Model'),
        ),
    ]
