# Generated by Django 2.0.2 on 2018-03-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Csisid', models.IntegerField()),
                ('Fname', models.CharField(max_length=500)),
                ('Lname', models.CharField(max_length=500)),
                ('Registered', models.IntegerField(default=0)),
                ('Registertime', models.DateTimeField()),
                ('Tracks', models.ManyToManyField(blank=True, to='track.Track')),
            ],
        ),
    ]
